version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"  # Adjusted to the port your frontend uses
    volumes:
      - ./client:/app
      - /app/node_modules  # Ensures node_modules are only inside the container
    environment:
      - NODE_ENV=development
    depends_on:
      - backend  # Ensures the backend starts before frontend

  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"  # Adjusted to the port your backend uses
    volumes:
      - ./server:/app
      - /app/node_modules  # Ensures node_modules are only inside the container
    environment:
      - NODE_ENV=development
      - FRONTEND_URL=http://client:5173  # Ensure the backend is configured to use this URL
