name: Test Project

on:
  pull_request:
    paths:
      - 'client/**' 

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install
        working-directory: client
        
      - name: Lint Test
        run: npm run lint
        working-directory: client

      - name: Build the Project
        run: npm run build
        working-directory: client
