version: "3.8"

services:
  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules #
    environment:
      - NODE_ENV=development
      - FRONTEND_URL=http://client:5173
