name: Enforce PRs
on: [push]
jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Block direct push
        run: |
          if [[ "${{ github.ref }}" != refs/pull/* ]]; then
            echo "Direct push is not allowed. Use a Pull Request!"
            exit 1
          fi
