name: Test Project

on:
  pull_request:
    branches:
      - master
      - main
      - prod
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build the Project
        run: npm run build
      
      
